create table public.habit (
  id bigint generated by default as identity not null,
  user_id uuid not null default auth.uid (),
  name text not null,
  color text not null,
  is_archived boolean not null default false,
  created_at timestamp with time zone not null default now(),
  "order" bigint null,
  constraint habit_pkey primary key (id),
  constraint habit_id_key unique (id),
  constraint habit_user_id_fkey foreign KEY (user_id) references auth.users (id)
) TABLESPACE pg_default;

create table public.habit_tag (
  id bigint generated by default as identity not null,
  habit_id bigint not null,
  name text not null,
  created_at timestamp with time zone not null default now(),
  constraint habit_tag_pkey primary key (id),
  constraint habit_tag_id_key unique (id),
  constraint habit_tag_habit_id_fkey foreign KEY (habit_id) references habit (id) on update CASCADE
) TABLESPACE pg_default;

create table public.event (
  id bigint generated by default as identity not null,
  habit_id bigint not null,
  date date not null,
  created_at timestamp with time zone not null default now(),
  constraint event_pkey primary key (id),
  constraint event_id_key unique (id),
  constraint event_habit_id_fkey foreign KEY (habit_id) references habit (id)
) TABLESPACE pg_default;

create table public.event_tag (
  id bigint generated by default as identity not null,
  event_id bigint not null,
  habit_tag_id bigint not null,
  created_at timestamp with time zone not null default now(),
  constraint event_tag_pkey primary key (id),
  constraint event_tag_id_key unique (id),
  constraint event_tag_event_id_fkey foreign KEY (event_id) references event (id) on update CASCADE on delete CASCADE,
  constraint event_tag_habit_tag_id_fkey foreign KEY (habit_tag_id) references habit_tag (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;